all : LiquidMedicine
LiquidMedicine : LiquidMedicine
	gcc -W -Wall -o LiquidMedicine LiquidMedicine.o
LiquidMedicine.o : LiquidMedicine.cpp
	gcc -W =Wall -c -o LiquidMedicine.o LiquidMedicine.cpp 
clean :
	rm -rf *.o LiquidMedicine
